# Default Setting

spring:
  application:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
    password: 1234
    username: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    generate-ddl: true
  main:
    allow-bean-definition-overriding: true

server:
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_KEY}
  expiration: 3600000 # 30분 in milliseconds

emitter :
  expiration: 3600000 # 30분 in milliseconds